In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [2]:
# Read loans data
link = 'https://spark-public.s3.amazonaws.com/dataanalysis/loansData.csv'

In [3]:
loan_data = pd.read_csv(link)
loan_data.head()

,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
81174,20000,20000.0,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year
99592,19200,19200.0,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years
80059,35000,35000.0,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years
15825,10000,9975.0,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years
33182,12000,12000.0,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years

In [4]:
y = loan_data['Interest.Rate']
x = loan_data.drop(['Interest.Rate'], axis = 1)
x = x.rename(index=str, columns={"Home.Ownership": "Home_Ownership", "Amount.Requested": "Amount_Requested", "Amount.Funded.By.Investors"
                            : "Amount_Funded_By_Investors", "Loan.Length":"Loan_Length", "Loan.Purpose": "Loan_Purpose",
                            "Debt.To.Income.Ratio": "Debt_To_Income_Ratio", "Home.Ownership":"Home_Ownership", "Monthly.Income"
                            : "Monthly_Income", "FICO.Range":"FICO_Range", "Open.CREDIT.Lines":"Open_CREDIT_Lines",
                            "Revolving.CREDIT.Balance": "Revolving_CREDIT_Balance", "Inquiries.in.the.Last.6.Months":
                            "Inquiries_in_the_Last_6_Months", "Employment.Length": "Employment_Length"})
print('Unique Loan_Purpose values:\n',x.Loan_Purpose.unique())
print('\n\nUnique Loan_Length values:\n', x.Loan_Length.unique())
print('\n\nDebt_To_Income_Ratio is of type ',type(x.Debt_To_Income_Ratio[0]), ' so I will convert that to int.\n\n')
print('\n\nUnique values in State:\n', x.State.unique())
print('\n\nUnique values in Home_Ownership:\n', x.Home_Ownership.unique())
print('\n\nUnique values in FICO_Range:\n', x.FICO_Range.unique())
# Int so do not have to convert. But will drop nans later
print('\n\nUnique values in Open_CREDIT_Lines:\n', x.Open_CREDIT_Lines.unique())
print('\n\nUnique values in Employment_Length:\n', x.Employment_Length.unique())
x.head()

Unique Loan_Purpose values:
 ['debt_consolidation' 'credit_card' 'other' 'moving' 'car' 'vacation'
 'home_improvement' 'house' 'major_purchase' 'educational' 'medical'
 'wedding' 'small_business' 'renewable_energy']


Unique Loan_Length values:
 ['36 months' '60 months']


Debt_To_Income_Ratio is of type  <class 'str'>  so I will convert that to int.




Unique values in State:
 ['SC' 'TX' 'CA' 'KS' 'NJ' 'CT' 'MA' 'LA' 'FL' 'DC' 'OH' 'AL' 'AZ' 'GA'
 'WV' 'NH' 'VA' 'NY' 'MD' 'HI' 'PA' 'WA' 'IL' 'NC' 'WI' 'SD' 'AK' 'DE'
 'MN' 'MO' 'RI' 'CO' 'NM' 'MI' 'OK' 'NV' 'UT' 'AR' 'KY' 'VT' 'OR' 'IA'
 'MT' 'IN' 'WY' 'MS']


Unique values in Home_Ownership:
 ['MORTGAGE' 'RENT' 'OWN' 'OTHER' 'NONE']


Unique values in FICO_Range:
 ['735-739' '715-719' '690-694' '695-699' '670-674' '720-724' '705-709'
 '685-689' '665-669' '725-729' '730-734' '740-744' '760-764' '675-679'
 '765-769' '780-784' '830-834' '660-664' '710-714' '785-789' '750-754'
 '700-704' '680-684' '755-759' '790-794' '810-814' '775-779' '815-819'
 '745-749' '805-809' '800-804' '655-659' '770-774' '795-799' '640-644'
 '645-649' '820-824' '650-654']


Unique values in Open_CREDIT_Lines:
 [14. 12. 10. 11. 17.  9.  8. 19. 13.  6. 18.  7.  5.  4. 23.  2.  3. 22.
 15. 21. 16. 20. nan 26. 31. 38. 25. 24. 34. 36.]


Unique values in Employment_Length:
 ['< 1 year' '2 years' '5 years' '9 years' '3 years' '10+ years' '8 years'
 '6 years' '1 year' '7 years' '4 years' nan]

,Amount_Requested,Amount_Funded_By_Investors,Loan_Length,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_Range,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length
81174,20000,20000.0,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year
99592,19200,19200.0,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years
80059,35000,35000.0,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years
15825,10000,9975.0,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years
33182,12000,12000.0,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years

# Manipulating Data Types

As seen above, there are many columns in our data set that are categorical data/ strings instead of integers. In order to fit my data to a linear regression model, I have to convert all data types to integers that will fit with the model

In [5]:
# The column titled 'Loan_Length' has 2 options: 36 months of 60 months. I will change these columns simply to 36 or 60.
x_loan = x.Loan_Length.replace('36 months', int(36)).replace('60 months', int(60)) 
x = x.drop(['Loan_Length'], axis = 1)#.insert(0, column = 'Loan_Length', value = x_loan)
x['Loan_Length'] = pd.Series(x_loan, index=x.index)
x

,Amount_Requested,Amount_Funded_By_Investors,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_Range,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length,Loan_Length
81174,20000,20000.00,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year,36
99592,19200,19200.00,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years,36
80059,35000,35000.00,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years,60
15825,10000,9975.00,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years,36
33182,12000,12000.00,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years,36
62403,6000,6000.00,other,20.05%,CT,OWN,4891.67,670-674,17.0,10391.0,2.0,3 years,36
48808,10000,10000.00,debt_consolidation,26.09%,MA,RENT,2916.67,720-724,10.0,15957.0,0.0,10+ years,36
22090,33500,33450.00,credit_card,14.70%,LA,MORTGAGE,13863.42,705-709,12.0,27874.0,0.0,10+ years,60
76404,14675,14675.00,credit_card,26.92%,CA,RENT,3150.00,685-689,9.0,7246.0,1.0,8 years,36
15867,7000,7000.00,credit_card,7.10%,CA,RENT,5000.00,715-719,8.0,7612.0,0.0,3 years,36
94971,2000,2000.00,moving,10.29%,FL,RENT,3575.00,670-674,10.0,12036.0,0.0,6 years,36
36911,10625,10625.00,debt_consolidation,12.54%,CA,MORTGAGE,4250.00,665-669,14.0,10767.0,0.0,< 1 year,36
41200,28000,27975.00,debt_consolidation,13.07%,CT,MORTGAGE,14166.67,670-674,12.0,10311.0,0.0,1 year,60
83869,35000,34950.00,debt_consolidation,20.46%,CT,RENT,9166.67,735-739,19.0,21536.0,0.0,1 year,36
53853,9600,9600.00,debt_consolidation,3.45%,DC,RENT,11250.00,725-729,13.0,4606.0,0.0,< 1 year,36
21399,25000,24975.00,debt_consolidation,21.99%,CA,RENT,5416.67,730-734,6.0,13929.0,0.0,9 years,60
62127,10000,10000.00,debt_consolidation,17.72%,CA,RENT,9000.00,695-699,18.0,20317.0,0.0,7 years,36
23446,14000,13900.25,debt_consolidation,11.95%,OH,RENT,4333.33,740-744,6.0,7419.0,0.0,9 years,60
44987,10000,10000.00,credit_card,7.13%,FL,RENT,2733.33,730-734,7.0,6112.0,2.0,3 years,36
17977,5200,5175.00,debt_consolidation,10.29%,AL,MORTGAGE,3750.00,760-764,10.0,16094.0,0.0,< 1 year,60
86099,22000,21975.00,debt_consolidation,11.19%,TX,MORTGAGE,6666.67,665-669,9.0,23124.0,0.0,10+ years,36
99483,30000,30000.00,credit_card,21.25%,FL,MORTGAGE,6250.00,695-699,12.0,34927.0,0.0,6 years,60
28798,6500,6500.00,car,19.63%,FL,RENT,4100.00,665-669,11.0,11697.0,1.0,2 years,60
24168,17400,17400.00,credit_card,12.47%,AZ,RENT,6833.33,695-699,7.0,26587.0,0.0,7 years,36
10356,4000,4000.00,vacation,13.71%,GA,MORTGAGE,4500.00,670-674,5.0,20804.0,0.0,3 years,60
46027,7200,7200.00,debt_consolidation,24.82%,TX,RENT,5416.67,705-709,8.0,12017.0,0.0,7 years,36
2238,8000,8000.00,debt_consolidation,24.63%,MA,RENT,2964.17,675-679,9.0,8928.0,2.0,6 years,36
65278,8000,8000.00,debt_consolidation,15.46%,CA,MORTGAGE,2916.67,675-679,13.0,7152.0,1.0,5 years,36
4227,3000,3000.00,other,3.72%,MA,MORTGAGE,4167.00,765-769,4.0,7074.0,0.0,5 years,36
50182,14500,14500.00,debt_consolidation,4.85%,GA,MORTGAGE,3958.33,760-764,4.0,9598.0,0.0,4 years,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84265,20000,20000.00,debt_consolidation,7.10%,NJ,RENT,6750.00,665-669,6.0,16104.0,1.0,7 years,60
80231,19000,19000.00,debt_consolidation,9.76%,RI,MORTGAGE,5166.67,770-774,18.0,43617.0,2.0,10+ years,36
49533,17300,17250.00,wedding,3.58%,PA,MORTGAGE,5500.00,685-689,11.0,2306.0,3.0,4 years,60
102514,7000,711.54,major_purchase,18.91%,CO,MORTGAGE,3833.00,650-654,13.0,12634.0,0.0,2 years,36
78618,7200,7200.00,debt_consolidation,16.21%,MI,RENT,8333.33,660-664,8.0,28916.0,0.0,10+ years,36
86953,10000,10000.00,major_purchase,9.71%,CO,RENT,4583.33,675-679,6.0,3859.0,0.0,< 1 year,36
80129,4000,3925.00,credit_card,12.27%,FL,MORTGAGE,8583.33,675-679,9.0,36943.0,1.0,10+ years,36
85216,17500,17500.00,debt_consolidation,10.94%,UT,MORTGAGE,25000.00,730-734,9.0,34545.0,0.0,6 years,36
38247,20000,20000.00,credit_card,9.58%,SD,MORTGAGE,5416.67,725-729,12.0,18267.0,1.0,4 years,36
91245,16200,16200.00,debt_consolidation,7.92%,PA,MORTGAGE,4833.33,680-684,12.0,12313.0,2.0,10+ years,60
53041,10000,10000.00,small_business,13.03%,FL,RENT,5000.00,760-764,8.0,3952.0,0.0,2 years,36
63051,27000,27000.00,debt_consolidation,12.21%,OH,MORTGAGE,9250.00,810-814,12.0,4211.0,0.0,5 years,36
14446,4500,4475.00,small_business,20.27%,VA,MORTGAGE,7075.50,720-724,15.0,68618.0,2.0,10+ years,36
68628,15875,15875.00,small_business,17.44%,MD,MORTGAGE,3416.67,675-679,11.0,15891.0,0.0,2 years,36
98758,15000,15000.00,credit_card,28.28%,OH,MORTGAGE,6666.67,690-694,15.0,14880.0,0.0,10+ years,36
13070,25000,24950.00,debt_consolidation,20.48%,OR,MORTGAGE,7083.33,765-769,10.0,25429.0,0.0,6 years,36
45836,7000,7000.00,other,18.38%,NY,OWN,2464.37,665-669,9.0,7089.0,0.0,3 years,36
52330,15000,15000.00,wedding,18.05%,CA,RENT,8000.00,660-664,6.0,45976.0,1.0,2 years,36
48243,17000,17000.00,debt_consolidation,17.01%,CO,RENT,3833.33,685-689,6.0,15484.0,1.0,6 years,36
63256,19075,19075.00,debt_consolidation,15.23%,NY,RENT,5166.67,670-674,17.0,13749.0,3.0,10+ years,36
42124,10000,10000.00,debt_consolidation,8.40%,CA,RENT,4500.00,710-714,8.0,8404.0,1.0,3 years,36
78043,8475,8475.00,debt_consolidation,15.88%,CA,RENT,3983.33,720-724,9.0,6882.0,0.0,NaN,36
925,6400,6350.00,debt_consolidation,8.11%,NJ,MORTGAGE,5166.67,710-714,5.0,5815.0,2.0,10+ years,36
74047,30000,30000.00,other,12.10%,IL,MORTGAGE,7083.33,675-679,16.0,17969.0,1.0,10+ years,60
49957,24000,23975.00,debt_consolidation,15.29%,WA,MORTGAGE,6666.67,685-689,13.0,17521.0,0.0,5 years,36
23735,30000,29950.00,debt_consolidation,19.23%,NY,MORTGAGE,9250.00,705-709,15.0,45880.0,1.0,8 years,60
65882,16000,16000.00,home_improvement,21.54%,MD,OWN,8903.25,740-744,18.0,18898.0,1.0,10+ years,60
55610,10000,10000.00,debt_consolidation,4.89%,PA,MORTGAGE,2166.67,680-684,4.0,4544.0,0.0,10+ years,36
38576,6000,6000.00,major_purchase,16.66%,NJ,RENT,3500.00,675-679,8.0,7753.0,0.0,5 years,36
3116,9000,5242.75,debt_consolidation,6.76%,NY,RENT,3875.00,670-674,7.0,7589.0,0.0,10+ years,36

Columns that are ints:

1. Open_CREDIT_Lines
2. Amount_Requested
3. Amount_Funded_By_Investors
4. Monthly_Income
5. Open_CREDIT_Lines
6. Revolving_CREDIT_Balance
7. Inquiries_in_the_Last_6_Months
8. Loan_Length
9. Debt_To_Income_Ratio
10. Employment_Length

In [6]:
wow = x.Debt_To_Income_Ratio.iloc[:,].str.strip('%')
wow = wow.astype(float)
wow = wow / 100
x = x.drop(['Debt_To_Income_Ratio'], axis = 1)
x['Debt_To_Income_Ratio'] = pd.Series(wow, index=x.index)

In [7]:
# Now to convert 'Employment_Length' to int values

x_emp = x.Employment_Length.str.strip('year').str.strip('years').str.replace('+', '').str.replace('< 1', '0.5').fillna(0).astype(float)
x = x.drop(['Employment_Length'], axis = 1)
x['Employment_Length'] = pd.Series(x_emp, index = x.index)

In [8]:
x = x.drop(['State'], axis = 1)

I am choosing to drop the state column because state populations are not equaly distributed and can result in unbalanced data

In [9]:
x.head()

,Amount_Requested,Amount_Funded_By_Investors,Loan_Purpose,Home_Ownership,Monthly_Income,FICO_Range,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Loan_Length,Debt_To_Income_Ratio,Employment_Length
81174,20000,20000.0,debt_consolidation,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,36,0.1490,0.5
99592,19200,19200.0,debt_consolidation,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,36,0.2836,2.0
80059,35000,35000.0,debt_consolidation,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,60,0.2381,2.0
15825,10000,9975.0,debt_consolidation,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,36,0.1430,5.0
33182,12000,12000.0,credit_card,RENT,3195.00,695-699,11.0,14469.0,0.0,36,0.1878,9.0

For the FICO_Range category, I will replace the range by the mean of values. Ex: '695-699' will turn to '697'


Unique values in FICO_Range:
 ['735-739' '715-719' '690-694' '695-699' '670-674' '720-724' '705-709'
 '685-689' '665-669' '725-729' '730-734' '740-744' '760-764' '675-679'
 '765-769' '780-784' '830-834' '660-664' '710-714' '785-789' '750-754'
 '700-704' '680-684' '755-759' '790-794' '810-814' '775-779' '815-819'
 '745-749' '805-809' '800-804' '655-659' '770-774' '795-799' '640-644'
 '645-649' '820-824' '650-654']

In [10]:
x_fic = []
for l in x.FICO_Range:
    life = l.split('-')
    value = (int(life[0]) + int(life[1])) / 2
    print(value)
    x_fic.append(value)
    
x['FICO_Range_Mean'] = pd.Series(x_fic, index = x.index)

737.0
717.0
692.0
697.0
697.0
672.0
722.0
707.0
687.0
717.0
672.0
667.0
672.0
737.0
727.0
732.0
697.0
742.0
732.0
762.0
667.0
697.0
667.0
697.0
672.0
707.0
677.0
677.0
767.0
762.0
687.0
687.0
722.0
687.0
677.0
782.0
722.0
832.0
717.0
662.0
672.0
722.0
662.0
662.0
677.0
717.0
712.0
672.0
787.0
707.0
752.0
662.0
702.0
667.0
682.0
727.0
672.0
717.0
692.0
757.0
707.0
717.0
682.0
667.0
732.0
727.0
687.0
687.0
707.0
697.0
697.0
717.0
737.0
667.0
672.0
672.0
792.0
702.0
667.0
727.0
712.0
762.0
682.0
692.0
697.0
727.0
812.0
677.0
752.0
687.0
667.0
767.0
672.0
677.0
677.0
752.0
767.0
737.0
667.0
672.0
702.0
707.0
742.0
692.0
722.0
767.0
717.0
712.0
692.0
712.0
777.0
817.0
747.0
662.0
692.0
712.0
727.0
677.0
767.0
737.0
702.0
737.0
692.0
762.0
682.0
697.0
677.0
702.0
697.0
677.0
732.0
667.0
677.0
682.0
727.0
662.0
807.0
747.0
742.0
702.0
722.0
662.0
737.0
702.0
707.0
727.0
662.0
737.0
727.0
707.0
672.0
722.0
717.0
707.0
712.0
692.0
707.0
687.0
662.0
667.0
747.0
742.0
667.0
697.0
682.0
702.0
717.0
712.0
722.0
667.0
702.0
687.0
727.0
687.0
682.0
752.0
802.0
742.0
732.0
722.0
702.0
697.0
697.0
702.0
672.0
747.0
677.0
742.0
662.0
732.0
747.0
702.0
677.0
667.0
732.0
747.0
757.0
792.0
727.0
672.0
667.0
687.0
752.0
717.0
702.0
752.0
732.0
757.0
692.0
692.0
737.0
702.0
692.0
677.0
667.0
732.0
707.0
682.0
762.0
727.0
687.0
712.0
667.0
722.0
662.0
752.0
712.0
732.0
667.0
692.0
672.0
662.0
672.0
667.0
667.0
752.0
722.0
682.0
687.0
762.0
702.0
697.0
752.0
682.0
752.0
792.0
742.0
717.0
712.0
727.0
762.0
732.0
687.0
707.0
672.0
677.0
672.0
702.0
667.0
667.0
752.0
722.0
732.0
802.0
807.0
682.0
732.0
727.0
697.0
692.0
697.0
717.0
667.0
672.0
667.0
687.0
672.0
717.0
717.0
722.0
667.0
782.0
707.0
692.0
672.0
707.0
677.0
687.0
677.0
732.0
682.0
672.0
752.0
747.0
657.0
692.0
692.0
777.0
752.0
667.0
662.0
732.0
802.0
757.0
792.0
687.0
752.0
697.0
687.0
772.0
707.0
797.0
717.0
687.0
667.0
707.0
662.0
742.0
682.0
732.0
787.0
757.0
667.0
667.0
662.0
687.0
682.0
702.0
672.0
732.0
672.0
712.0
712.0
757.0
782.0
717.0
712.0
687.0
692.0
662.0
787.0
722.0
722.0
712.0
677.0
692.0
687.0
677.0
677.0
692.0
692.0
792.0
712.0
677.0
762.0
672.0
717.0
742.0
677.0
697.0
712.0
712.0
687.0
692.0
737.0
662.0
802.0
712.0
742.0
737.0
692.0
662.0
772.0
757.0
712.0
667.0
702.0
707.0
792.0
687.0
692.0
717.0
707.0
702.0
727.0
692.0
722.0
692.0
722.0
687.0
667.0
702.0
682.0
672.0
682.0
672.0
692.0
702.0
782.0
777.0
737.0
687.0
757.0
717.0
732.0
682.0
672.0
687.0
752.0
707.0
682.0
677.0
667.0
697.0
692.0
702.0
702.0
702.0
732.0
717.0
692.0
677.0
727.0
732.0
737.0
687.0
672.0
687.0
717.0
707.0
692.0
697.0
717.0
712.0
737.0
762.0
717.0
707.0
727.0
732.0
677.0
697.0
662.0
762.0
682.0
732.0
732.0
707.0
722.0
707.0
687.0
672.0
732.0
732.0
687.0
702.0
677.0
667.0
722.0
727.0
702.0
672.0
782.0
727.0
722.0
662.0
702.0
687.0
732.0
682.0
682.0
742.0
672.0
782.0
732.0
692.0
697.0
662.0
667.0
697.0
682.0
687.0
692.0
677.0
667.0
722.0
667.0
717.0
692.0
707.0
707.0
677.0
727.0
677.0
692.0
672.0
727.0
702.0
672.0
682.0
672.0
702.0
682.0
692.0
687.0
677.0
747.0
682.0
687.0
672.0
737.0
732.0
692.0
727.0
762.0
747.0
777.0
712.0
762.0
717.0
717.0
752.0
702.0
757.0
672.0
667.0
752.0
672.0
677.0
682.0
672.0
777.0
667.0
662.0
667.0
677.0
682.0
682.0
672.0
732.0
707.0
742.0
687.0
672.0
722.0
687.0
677.0
727.0
742.0
717.0
672.0
702.0
687.0
687.0
662.0
722.0
672.0
712.0
742.0
682.0
742.0
667.0
712.0
687.0
672.0
697.0
722.0
772.0
707.0
672.0
692.0
732.0
687.0
692.0
697.0
727.0
732.0
677.0
682.0
722.0
692.0
667.0
692.0
662.0
682.0
687.0
697.0
692.0
737.0
762.0
752.0
792.0
742.0
722.0
662.0
702.0
702.0
682.0
692.0
702.0
672.0
782.0
667.0
702.0
707.0
677.0
687.0
687.0
692.0
802.0
727.0
692.0
752.0
702.0
792.0
687.0
722.0
677.0
707.0
682.0
737.0
707.0
677.0
742.0
757.0
707.0
712.0
702.0
787.0
692.0
672.0
712.0
722.0
702.0
697.0
722.0
712.0
697.0
717.0
727.0
737.0
712.0
677.0
677.0
712.0
732.0
732.0
722.0
642.0
702.0
682.0
737.0
722.0
677.0
692.0
727.0
722.0
732.0
712.0
762.0
797.0
662.0
682.0
697.0
737.0
672.0
687.0
707.0
692.0
697.0
667.0
682.0
747.0
687.0
667.0
747.0
677.0
727.0
727.0
712.0
727.0
692.0
672.0
697.0
722.0
787.0
677.0
697.0
687.0
667.0
662.0
702.0
692.0
667.0
702.0
722.0
672.0
727.0
707.0
692.0
747.0
642.0
707.0
667.0
667.0
677.0
782.0
692.0
667.0
667.0
677.0
682.0
662.0
717.0
712.0
672.0
777.0
682.0
667.0
667.0
677.0
712.0
697.0
682.0
712.0
717.0
672.0
717.0
697.0
672.0
687.0
697.0
677.0
697.0
682.0
772.0
737.0
717.0
722.0
667.0
687.0
682.0
672.0
677.0
672.0
727.0
662.0
702.0
677.0
707.0
692.0
722.0
667.0
682.0
677.0
682.0
672.0
682.0
687.0
682.0
692.0
722.0
667.0
732.0
672.0
682.0
667.0
662.0
707.0
692.0
722.0
702.0
707.0
722.0
712.0
662.0
712.0
667.0
747.0
712.0
747.0
662.0
732.0
732.0
672.0
732.0
707.0
732.0
667.0
702.0
672.0
747.0
672.0
702.0
727.0
702.0
672.0
667.0
747.0
712.0
672.0
722.0
707.0
682.0
717.0
737.0
792.0
757.0
752.0
682.0
672.0
662.0
687.0
672.0
727.0
782.0
692.0
707.0
687.0
722.0
662.0
667.0
682.0
677.0
767.0
702.0
702.0
732.0
727.0
662.0
712.0
702.0
792.0
777.0
692.0
747.0
732.0
677.0
692.0
682.0
742.0
672.0
782.0
812.0
702.0
697.0
672.0
722.0
767.0
762.0
682.0
677.0
687.0
722.0
677.0
767.0
667.0
692.0
677.0
682.0
702.0
722.0
737.0
707.0
752.0
702.0
662.0
772.0
662.0
717.0
677.0
742.0
697.0
727.0
782.0
707.0
747.0
737.0
667.0
672.0
702.0
672.0
787.0
707.0
742.0
747.0
767.0
682.0
697.0
697.0
707.0
732.0
692.0
772.0
727.0
727.0
717.0
672.0
672.0
692.0
667.0
782.0
687.0
782.0
677.0
672.0
677.0
737.0
732.0
722.0
677.0
677.0
667.0
672.0
677.0
687.0
702.0
737.0
752.0
772.0
672.0
762.0
677.0
732.0
707.0
732.0
662.0
687.0
712.0
697.0
742.0
697.0
762.0
682.0
722.0
672.0
712.0
722.0
687.0
677.0
677.0
692.0
732.0
712.0
697.0
682.0
732.0
702.0
697.0
702.0
742.0
707.0
767.0
727.0
757.0
702.0
692.0
662.0
712.0
722.0
707.0
667.0
712.0
752.0
697.0
672.0
712.0
702.0
767.0
727.0
702.0
767.0
667.0
697.0
712.0
702.0
747.0
707.0
677.0
762.0
687.0
742.0
792.0
677.0
752.0
762.0
692.0
672.0
712.0
662.0
662.0
667.0
727.0
697.0
687.0
757.0
682.0
672.0
697.0
732.0
762.0
707.0
687.0
722.0
677.0
792.0
722.0
737.0
792.0
687.0
682.0
747.0
692.0
687.0
697.0
697.0
737.0
717.0
662.0
682.0
692.0
677.0
697.0
707.0
697.0
727.0
677.0
737.0
677.0
707.0
697.0
677.0
697.0
732.0
687.0
672.0
662.0
692.0
787.0
787.0
692.0
697.0
712.0
667.0
767.0
672.0
722.0
712.0
747.0
677.0
682.0
722.0
682.0
692.0
687.0
672.0
682.0
732.0
697.0
702.0
762.0
722.0
667.0
682.0
702.0
737.0
707.0
782.0
692.0
662.0
717.0
662.0
682.0
682.0
717.0
682.0
672.0
717.0
682.0
732.0
762.0
747.0
722.0
707.0
682.0
677.0
712.0
672.0
717.0
672.0
722.0
707.0
762.0
677.0
697.0
677.0
722.0
682.0
712.0
752.0
697.0
677.0
807.0
727.0
722.0
687.0
662.0
677.0
697.0
732.0
797.0
672.0
687.0
667.0
682.0
672.0
702.0
727.0
722.0
697.0
767.0
767.0
752.0
662.0
767.0
742.0
672.0
677.0
742.0
677.0
747.0
722.0
757.0
722.0
672.0
767.0
662.0
667.0
662.0
677.0
757.0
717.0
772.0
717.0
707.0
762.0
682.0
717.0
687.0
687.0
662.0
722.0
757.0
677.0
697.0
752.0
702.0
692.0
692.0
702.0
792.0
742.0
712.0
657.0
752.0
712.0
767.0
707.0
717.0
672.0
747.0
727.0
757.0
747.0
717.0
762.0
717.0
662.0
712.0
672.0
697.0
672.0
692.0
722.0
707.0
712.0
677.0
697.0
727.0
757.0
722.0
697.0
752.0
707.0
712.0
672.0
677.0
732.0
707.0
667.0
677.0
772.0
732.0
702.0
742.0
697.0
712.0
747.0
667.0
737.0
697.0
697.0
707.0
697.0
712.0
757.0
697.0
682.0
677.0
692.0
687.0
697.0
672.0
777.0
687.0
702.0
707.0
747.0
727.0
672.0
677.0
712.0
732.0
752.0
717.0
672.0
712.0
717.0
702.0
712.0
772.0
737.0
727.0
697.0
727.0
677.0
757.0
662.0
687.0
647.0
762.0
732.0
687.0
682.0
677.0
697.0
707.0
677.0
732.0
767.0
682.0
677.0
707.0
667.0
692.0
717.0
697.0
667.0
722.0
692.0
702.0
672.0
667.0
707.0
702.0
697.0
662.0
757.0
717.0
692.0
707.0
662.0
692.0
727.0
702.0
677.0
777.0
682.0
752.0
687.0
762.0
767.0
707.0
762.0
727.0
812.0
687.0
717.0
752.0
687.0
702.0
702.0
662.0
667.0
647.0
682.0
697.0
672.0
802.0
737.0
687.0
747.0
667.0
717.0
802.0
697.0
692.0
712.0
767.0
712.0
672.0
787.0
697.0
697.0
707.0
802.0
732.0
702.0
732.0
752.0
707.0
677.0
712.0
777.0
732.0
662.0
722.0
732.0
732.0
787.0
697.0
772.0
707.0
782.0
672.0
687.0
757.0
692.0
762.0
672.0
702.0
707.0
662.0
782.0
667.0
762.0
697.0
667.0
662.0
727.0
677.0
697.0
757.0
687.0
687.0
752.0
707.0
757.0
742.0
722.0
752.0
672.0
702.0
692.0
722.0
662.0
682.0
732.0
722.0
737.0
682.0
737.0
787.0
702.0
647.0
722.0
682.0
752.0
677.0
677.0
727.0
782.0
737.0
662.0
722.0
717.0
737.0
762.0
727.0
737.0
687.0
662.0
722.0
692.0
677.0

672.0
787.0
672.0
717.0
767.0
732.0
692.0
662.0
747.0
767.0
717.0
767.0
702.0
727.0
697.0
787.0
672.0
792.0
727.0
797.0
672.0
732.0
712.0
662.0
697.0
722.0
677.0
707.0
722.0
762.0
687.0
667.0
727.0
662.0
712.0
662.0
752.0
672.0
717.0
722.0
707.0
802.0
667.0
752.0
717.0
707.0
687.0
672.0
667.0
737.0
682.0
682.0
697.0
667.0
672.0
677.0
702.0
682.0
762.0
687.0
687.0
677.0
792.0
677.0
662.0
662.0
742.0
747.0
697.0
667.0
722.0
692.0
677.0
747.0
732.0
682.0
672.0
722.0
682.0
682.0
692.0
697.0
662.0
702.0
692.0
667.0
662.0
732.0
682.0
672.0
707.0
762.0
702.0
677.0
697.0
697.0
677.0
682.0
697.0
667.0
672.0
707.0
727.0
757.0
707.0
697.0
727.0
702.0
727.0
782.0
682.0
682.0
677.0
712.0
687.0
777.0
682.0
707.0
702.0
707.0
702.0
672.0
667.0
737.0
717.0
727.0
697.0
732.0
737.0
682.0
747.0
752.0
687.0
682.0
727.0
672.0
692.0
702.0
667.0
692.0
677.0
707.0
717.0
717.0
737.0
747.0
662.0
667.0
662.0
717.0
687.0
732.0
662.0
772.0
682.0
697.0
737.0
692.0
702.0
717.0
702.0
702.0
687.0
707.0
712.0
767.0
682.0
687.0
697.0
712.0
722.0
687.0
757.0
672.0
747.0
672.0
752.0
662.0
732.0
707.0
777.0
727.0
737.0
797.0
687.0
707.0
662.0
742.0
712.0
687.0
692.0
677.0
662.0
732.0
702.0
722.0
667.0
692.0
707.0
752.0
707.0
722.0
807.0
687.0
672.0
742.0
682.0
727.0
702.0
667.0
757.0
667.0
687.0
752.0
737.0
742.0
817.0
697.0
782.0
697.0
682.0
672.0
737.0
767.0
667.0
692.0
712.0
642.0
732.0
742.0
712.0
727.0
667.0
727.0
697.0
697.0
672.0
762.0
792.0
682.0
697.0
732.0
722.0
667.0
757.0
662.0
747.0
662.0
662.0
762.0
722.0
667.0
757.0
812.0
702.0
767.0
707.0
692.0
822.0
677.0
687.0
687.0
707.0
672.0
672.0
702.0
692.0
677.0
667.0
682.0
717.0
712.0
687.0
707.0
732.0
732.0
677.0
667.0
697.0
702.0
812.0
642.0
682.0
777.0
682.0
682.0
672.0
677.0
727.0
662.0
697.0
672.0
817.0
732.0
687.0
707.0
707.0
717.0
732.0
697.0
662.0
712.0
682.0
707.0
682.0
777.0
687.0
757.0
682.0
682.0
722.0
747.0
737.0
687.0
762.0
687.0
687.0
727.0
697.0
697.0
707.0
777.0
702.0
692.0
717.0
667.0
687.0
692.0
722.0
742.0
672.0
687.0
742.0
702.0
697.0
677.0
722.0
662.0
732.0
667.0
677.0
702.0
682.0
732.0
712.0
692.0
702.0
752.0
667.0
662.0
692.0
672.0
722.0
697.0
677.0
717.0
712.0
662.0
657.0
702.0
677.0
757.0
727.0
672.0
702.0
772.0
722.0
752.0
807.0
682.0
702.0
712.0
702.0
697.0
682.0
747.0
717.0
712.0
802.0
687.0
697.0
677.0
727.0
662.0
717.0
682.0
687.0
687.0
712.0
662.0
702.0
717.0
757.0
707.0
702.0
697.0
692.0
727.0
742.0
667.0
697.0
752.0
717.0
722.0
712.0
717.0
757.0
742.0
707.0
782.0
702.0
707.0
667.0
757.0
697.0
677.0
687.0
682.0
662.0
672.0
712.0
707.0
722.0
727.0
727.0
702.0
697.0
702.0
672.0
702.0
682.0
727.0
672.0
682.0
722.0
702.0
702.0
692.0
687.0
692.0
682.0
672.0
717.0
747.0
687.0
682.0
807.0
812.0
727.0
672.0
687.0
742.0
667.0
807.0
677.0
682.0
732.0
682.0
662.0
682.0
777.0
792.0
677.0
742.0
682.0
717.0
672.0
762.0
712.0
707.0
707.0
672.0
707.0
697.0
692.0
752.0
692.0
727.0
672.0
682.0
747.0
732.0
672.0
707.0
727.0
757.0
782.0
732.0
707.0
667.0
672.0
737.0
742.0
692.0
687.0
707.0
717.0
762.0
677.0
717.0
692.0
697.0
747.0
747.0
717.0
662.0
787.0
702.0
682.0
697.0
692.0
722.0
707.0
702.0
667.0
697.0
687.0
712.0
662.0
667.0
782.0
717.0
707.0
677.0
702.0
722.0
682.0
682.0
702.0
697.0
762.0
677.0
722.0
737.0
687.0
777.0
677.0
752.0
697.0
757.0
662.0
712.0
702.0
737.0
672.0
817.0
732.0
717.0
702.0
692.0
717.0
687.0
722.0
797.0
707.0
667.0
667.0
667.0
712.0
692.0
677.0
727.0
692.0
697.0
722.0
692.0
717.0
707.0
752.0
667.0
712.0
747.0
687.0
677.0
662.0
657.0
757.0
712.0
712.0
747.0
757.0
682.0
682.0
672.0
782.0
717.0
707.0
712.0
712.0
712.0
712.0
752.0
682.0
707.0
677.0
742.0
702.0
682.0
662.0
707.0
672.0
682.0
692.0
712.0
667.0
712.0
682.0
717.0
697.0
672.0
667.0
692.0
752.0
697.0
707.0
677.0
677.0
742.0
677.0
697.0
692.0
722.0
667.0
807.0
792.0
692.0
717.0
682.0
662.0
772.0
737.0
687.0
737.0
667.0
677.0
737.0
722.0
782.0
737.0
692.0
667.0
677.0
757.0
672.0
672.0
752.0
747.0
717.0
692.0
797.0
667.0
677.0
672.0
747.0
807.0
737.0
722.0
772.0
672.0
752.0
697.0
727.0
682.0
732.0
682.0
777.0
667.0
677.0
797.0
682.0
667.0
742.0
787.0
667.0
802.0
757.0
667.0
677.0
672.0
667.0
687.0
747.0
697.0
682.0
687.0
672.0
677.0
677.0
662.0
672.0
667.0
767.0
662.0
707.0
687.0
692.0
777.0
672.0
707.0
682.0
687.0
682.0
707.0
727.0
697.0
692.0
712.0
722.0
667.0
662.0
702.0
672.0
717.0
702.0
667.0
697.0
682.0
817.0
757.0
702.0
717.0
677.0
687.0
682.0
692.0
662.0
752.0
797.0
687.0
797.0
667.0
732.0
742.0
677.0
722.0
712.0
707.0
702.0
692.0
707.0
692.0
662.0
697.0
677.0
697.0
662.0
692.0
662.0
742.0
722.0
672.0
702.0
737.0
697.0
707.0
667.0
687.0
642.0
702.0
767.0
747.0
662.0
692.0
722.0
707.0
732.0
677.0
677.0
787.0
757.0
687.0
742.0
717.0
797.0
677.0
742.0
762.0
727.0
752.0
802.0
762.0
697.0
702.0
687.0
697.0
677.0
787.0
662.0
677.0
662.0
767.0
682.0
707.0
672.0
672.0
707.0
677.0
727.0
732.0
672.0
722.0
677.0
727.0
707.0
662.0
697.0
767.0
682.0
687.0
767.0
712.0
697.0
697.0
672.0
747.0
707.0
737.0
757.0
692.0
662.0
782.0
737.0
682.0
702.0
667.0
707.0
677.0
687.0
697.0
662.0
662.0
692.0
697.0
682.0
662.0
797.0
722.0
752.0
732.0
702.0
697.0
667.0
692.0
677.0
687.0
692.0
667.0
737.0
672.0
722.0
672.0
712.0
712.0
682.0
677.0
677.0
677.0
682.0
762.0
732.0
737.0
747.0
777.0
752.0
672.0
697.0
687.0
672.0
762.0
702.0
737.0
707.0
727.0
737.0
682.0
677.0
697.0
742.0
672.0
697.0
697.0
687.0
702.0
692.0
677.0
677.0
667.0
682.0
662.0
672.0
662.0
662.0
722.0
707.0
672.0
722.0
692.0
667.0
667.0
682.0
797.0
727.0
697.0
767.0
672.0
742.0
697.0
707.0
692.0
717.0
697.0
677.0
772.0
717.0
747.0
672.0
672.0
672.0
697.0
722.0
712.0
662.0
752.0
787.0
697.0
722.0
697.0
732.0
722.0
667.0
662.0
727.0
682.0
747.0
682.0
702.0
812.0
682.0
782.0
677.0
667.0
692.0
752.0
782.0
692.0
692.0
727.0
707.0
692.0
662.0
692.0
702.0
707.0
807.0
682.0
727.0
807.0
732.0
697.0
667.0
787.0
697.0
672.0
727.0
737.0
717.0
662.0
682.0
712.0
767.0
727.0
707.0
727.0
672.0
712.0
712.0
712.0
682.0
667.0
742.0
757.0
712.0
697.0
777.0
707.0
697.0
677.0
697.0
677.0
662.0
802.0
752.0
682.0
817.0
747.0
707.0
692.0
662.0
692.0
707.0
727.0
677.0
712.0
677.0
777.0
792.0
712.0
742.0
737.0
662.0
662.0
732.0
662.0
682.0
672.0
697.0
762.0
667.0
722.0
672.0
667.0
662.0
692.0
747.0
672.0
662.0
677.0
702.0
697.0
702.0
677.0
712.0
752.0
687.0
667.0
692.0
707.0
677.0
662.0
752.0
727.0
742.0
717.0
682.0
667.0
712.0
667.0
767.0
782.0
682.0
692.0
712.0
707.0
687.0
722.0
712.0
722.0
692.0
737.0
687.0
757.0
672.0
732.0
717.0
757.0
667.0
772.0
687.0
652.0
662.0
677.0
677.0
732.0
727.0
682.0
762.0
812.0
722.0
677.0
692.0
767.0
667.0
662.0
687.0
672.0
712.0
722.0
712.0
677.0
687.0
707.0
742.0
682.0
677.0
672.0

In [11]:
x = x.drop(['FICO_Range'], axis = 1)
x.head()

,Amount_Requested,Amount_Funded_By_Investors,Loan_Purpose,Home_Ownership,Monthly_Income,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Loan_Length,Debt_To_Income_Ratio,Employment_Length,FICO_Range_Mean
81174,20000,20000.0,debt_consolidation,MORTGAGE,6541.67,14.0,14272.0,2.0,36,0.1490,0.5,737.0
99592,19200,19200.0,debt_consolidation,MORTGAGE,4583.33,12.0,11140.0,1.0,36,0.2836,2.0,717.0
80059,35000,35000.0,debt_consolidation,MORTGAGE,11500.00,14.0,21977.0,1.0,60,0.2381,2.0,692.0
15825,10000,9975.0,debt_consolidation,MORTGAGE,3833.33,10.0,9346.0,0.0,36,0.1430,5.0,697.0
33182,12000,12000.0,credit_card,RENT,3195.00,11.0,14469.0,0.0,36,0.1878,9.0,697.0

Unique values in Home_Ownership:
 ['MORTGAGE' 'RENT' 'OWN' 'OTHER' 'NONE']

In [12]:
x_dummy = pd.get_dummies(x['Home_Ownership'])
print(x_dummy)

        MORTGAGE  NONE  OTHER  OWN  RENT
81174          1     0      0    0     0
99592          1     0      0    0     0
80059          1     0      0    0     0
15825          1     0      0    0     0
33182          0     0      0    0     1
62403          0     0      0    1     0
48808          0     0      0    0     1
22090          1     0      0    0     0
76404          0     0      0    0     1
15867          0     0      0    0     1
94971          0     0      0    0     1
36911          1     0      0    0     0
41200          1     0      0    0     0
83869          0     0      0    0     1
53853          0     0      0    0     1
21399          0     0      0    0     1
62127          0     0      0    0     1
23446          0     0      0    0     1
44987          0     0      0    0     1
17977          1     0      0    0     0
86099          1     0      0    0     0
99483          1     0      0    0     0
28798          0     0      0    0     1
24168          0     0      0    0     1
10356          1     0      0    0     0
46027          0     0      0    0     1
2238           0     0      0    0     1
65278          1     0      0    0     0
4227           1     0      0    0     0
50182          1     0      0    0     0
...          ...   ...    ...  ...   ...
84265          0     0      0    0     1
80231          1     0      0    0     0
49533          1     0      0    0     0
102514         1     0      0    0     0
78618          0     0      0    0     1
86953          0     0      0    0     1
80129          1     0      0    0     0
85216          1     0      0    0     0
38247          1     0      0    0     0
91245          1     0      0    0     0
53041          0     0      0    0     1
63051          1     0      0    0     0
14446          1     0      0    0     0
68628          1     0      0    0     0
98758          1     0      0    0     0
13070          1     0      0    0     0
45836          0     0      0    1     0
52330          0     0      0    0     1
48243          0     0      0    0     1
63256          0     0      0    0     1
42124          0     0      0    0     1
78043          0     0      0    0     1
925            1     0      0    0     0
74047          1     0      0    0     0
49957          1     0      0    0     0
23735          1     0      0    0     0
65882          0     0      0    1     0
55610          1     0      0    0     0
38576          0     0      0    0     1
3116           0     0      0    0     1

[2500 rows x 5 columns]

In [13]:
x = x.drop(['Home_Ownership'], axis = 1)

In [14]:
x = pd.concat([x, x_dummy], axis = 1)
x.head()

,Amount_Requested,Amount_Funded_By_Investors,Loan_Purpose,Monthly_Income,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Loan_Length,Debt_To_Income_Ratio,Employment_Length,FICO_Range_Mean,MORTGAGE,NONE,OTHER,OWN,RENT
81174,20000,20000.0,debt_consolidation,6541.67,14.0,14272.0,2.0,36,0.1490,0.5,737.0,1,0,0,0,0
99592,19200,19200.0,debt_consolidation,4583.33,12.0,11140.0,1.0,36,0.2836,2.0,717.0,1,0,0,0,0
80059,35000,35000.0,debt_consolidation,11500.00,14.0,21977.0,1.0,60,0.2381,2.0,692.0,1,0,0,0,0
15825,10000,9975.0,debt_consolidation,3833.33,10.0,9346.0,0.0,36,0.1430,5.0,697.0,1,0,0,0,0
33182,12000,12000.0,credit_card,3195.00,11.0,14469.0,0.0,36,0.1878,9.0,697.0,0,0,0,0,1

In [15]:
x.head()

,Amount_Requested,Amount_Funded_By_Investors,Loan_Purpose,Monthly_Income,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Loan_Length,Debt_To_Income_Ratio,Employment_Length,FICO_Range_Mean,MORTGAGE,NONE,OTHER,OWN,RENT
81174,20000,20000.0,debt_consolidation,6541.67,14.0,14272.0,2.0,36,0.1490,0.5,737.0,1,0,0,0,0
99592,19200,19200.0,debt_consolidation,4583.33,12.0,11140.0,1.0,36,0.2836,2.0,717.0,1,0,0,0,0
80059,35000,35000.0,debt_consolidation,11500.00,14.0,21977.0,1.0,60,0.2381,2.0,692.0,1,0,0,0,0
15825,10000,9975.0,debt_consolidation,3833.33,10.0,9346.0,0.0,36,0.1430,5.0,697.0,1,0,0,0,0
33182,12000,12000.0,credit_card,3195.00,11.0,14469.0,0.0,36,0.1878,9.0,697.0,0,0,0,0,1

In [16]:
x_dummy_purpose = pd.get_dummies(x['Loan_Purpose'])
print(x_dummy_purpose)

        car  credit_card  debt_consolidation  educational  home_improvement  \
81174     0            0                   1            0                 0
99592     0            0                   1            0                 0
80059     0            0                   1            0                 0
15825     0            0                   1            0                 0
33182     0            1                   0            0                 0
62403     0            0                   0            0                 0
48808     0            0                   1            0                 0
22090     0            1                   0            0                 0
76404     0            1                   0            0                 0
15867     0            1                   0            0                 0
94971     0            0                   0            0                 0
36911     0            0                   1            0                 0
41200     0            0                   1            0                 0
83869     0            0                   1            0                 0
53853     0            0                   1            0                 0
21399     0            0                   1            0                 0
62127     0            0                   1            0                 0
23446     0            0                   1            0                 0
44987     0            1                   0            0                 0
17977     0            0                   1            0                 0
86099     0            0                   1            0                 0
99483     0            1                   0            0                 0
28798     1            0                   0            0                 0
24168     0            1                   0            0                 0
10356     0            0                   0            0                 0
46027     0            0                   1            0                 0
2238      0            0                   1            0                 0
65278     0            0                   1            0                 0
4227      0            0                   0            0                 0
50182     0            0                   1            0                 0
...     ...          ...                 ...          ...               ...
84265     0            0                   1            0                 0
80231     0            0                   1            0                 0
49533     0            0                   0            0                 0
102514    0            0                   0            0                 0
78618     0            0                   1            0                 0
86953     0            0                   0            0                 0
80129     0            1                   0            0                 0
85216     0            0                   1            0                 0
38247     0            1                   0            0                 0
91245     0            0                   1            0                 0
53041     0            0                   0            0                 0
63051     0            0                   1            0                 0
14446     0            0                   0            0                 0
68628     0            0                   0            0                 0
98758     0            1                   0            0                 0
13070     0            0                   1            0                 0
45836     0            0                   0            0                 0
52330     0            0                   0            0                 0
48243     0            0                   1            0                 0
63256     0            0                   1            0                 0
42124     0            0                   1            0                 0
78043     0            0                   1            0                 0
925       0            0                   1            0                 0
74047     0            0                   0            0                 0
49957     0            0                   1            0                 0
23735     0            0                   1            0                 0
65882     0            0                   0            0                 1
55610     0            0                   1            0                 0
38576     0            0                   0            0                 0
3116      0            0                   1            0                 0

        house  major_purchase  medical  moving  other  renewable_energy  \
81174       0               0        0       0      0                 0
99592       0               0        0       0      0                 0
80059       0               0        0       0      0                 0
15825       0               0        0       0      0                 0
33182       0               0        0       0      0                 0
62403       0               0        0       0      1                 0
48808       0               0        0       0      0                 0
22090       0               0        0       0      0                 0
76404       0               0        0       0      0                 0
15867       0               0        0       0      0                 0
94971       0               0        0       1      0                 0
36911       0               0        0       0      0                 0
41200       0               0        0       0      0                 0
83869       0               0        0       0      0                 0
53853       0               0        0       0      0                 0
21399       0               0        0       0      0                 0
62127       0               0        0       0      0                 0
23446       0               0        0       0      0                 0
44987       0               0        0       0      0                 0
17977       0               0        0       0      0                 0
86099       0               0        0       0      0                 0
99483       0               0        0       0      0                 0
28798       0               0        0       0      0                 0
24168       0               0        0       0      0                 0
10356       0               0        0       0      0                 0
46027       0               0        0       0      0                 0
2238        0               0        0       0      0                 0
65278       0               0        0       0      0                 0
4227        0               0        0       0      1                 0
50182       0               0        0       0      0                 0
...       ...             ...      ...     ...    ...               ...
84265       0               0        0       0      0                 0
80231       0               0        0       0      0                 0
49533       0               0        0       0      0                 0
102514      0               1        0       0      0                 0
78618       0               0        0       0      0                 0
86953       0               1        0       0      0                 0
80129       0               0        0       0      0                 0
85216       0               0        0       0      0                 0
38247       0               0        0       0      0                 0
91245       0               0        0       0      0                 0
53041       0               0        0       0      0                 0
63051       0               0        0       0      0                 0
14446       0               0        0       0      0                 0
68628       0               0        0       0      0                 0
98758       0               0        0       0      0                 0
13070       0               0        0       0      0                 0
45836       0               0        0       0      1                 0
52330       0               0        0       0      0                 0
48243       0               0        0       0      0                 0
63256       0               0        0       0      0                 0
42124       0               0        0       0      0                 0
78043       0               0        0       0      0                 0
925         0               0        0       0      0                 0
74047       0               0        0       0      1                 0
49957       0               0        0       0      0                 0
23735       0               0        0       0      0                 0
65882       0               0        0       0      0                 0
55610       0               0        0       0      0                 0
38576       0               1        0       0      0                 0
3116        0               0        0       0      0                 0

        small_business  vacation  wedding
81174                0         0        0
99592                0         0        0
80059                0         0        0
15825                0         0        0
33182                0         0        0
62403                0         0        0
48808                0         0        0
22090                0         0        0
76404                0         0        0
15867                0         0        0
94971                0         0        0
36911                0         0        0
41200                0         0        0
83869                0         0        0
53853                0         0        0
21399                0         0        0
62127                0         0        0
23446                0         0        0
44987                0         0        0
17977                0         0        0
86099                0         0        0
99483                0         0        0
28798                0         0        0
24168                0         0        0
10356                0         1        0
46027                0         0        0
2238                 0         0        0
65278                0         0        0
4227                 0         0        0
50182                0         0        0
...                ...       ...      ...
84265                0         0        0
80231                0         0        0
49533                0         0        1
102514               0         0        0
78618                0         0        0
86953                0         0        0
80129                0         0        0
85216                0         0        0
38247                0         0        0
91245                0         0        0
53041                1         0        0
63051                0         0        0
14446                1         0        0
68628                1         0        0
98758                0         0        0
13070                0         0        0
45836                0         0        0
52330                0         0        1
48243                0         0        0
63256                0         0        0
42124                0         0        0
78043                0         0        0
925                  0         0        0
74047                0         0        0
49957                0         0        0
23735                0         0        0
65882                0         0        0
55610                0         0        0
38576                0         0        0
3116                 0         0        0

[2500 rows x 14 columns]

In [17]:
x = pd.concat([x, x_dummy_purpose], axis = 1).drop(['Loan_Purpose'], axis = 1)
x.head()

,Amount_Requested,Amount_Funded_By_Investors,Monthly_Income,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Loan_Length,Debt_To_Income_Ratio,Employment_Length,FICO_Range_Mean,...,home_improvement,house,major_purchase,medical,moving,other,renewable_energy,small_business,vacation,wedding
81174,20000,20000.0,6541.67,14.0,14272.0,2.0,36,0.1490,0.5,737.0,...,0,0,0,0,0,0,0,0,0,0
99592,19200,19200.0,4583.33,12.0,11140.0,1.0,36,0.2836,2.0,717.0,...,0,0,0,0,0,0,0,0,0,0
80059,35000,35000.0,11500.00,14.0,21977.0,1.0,60,0.2381,2.0,692.0,...,0,0,0,0,0,0,0,0,0,0
15825,10000,9975.0,3833.33,10.0,9346.0,0.0,36,0.1430,5.0,697.0,...,0,0,0,0,0,0,0,0,0,0
33182,12000,12000.0,3195.00,11.0,14469.0,0.0,36,0.1878,9.0,697.0,...,0,0,0,0,0,0,0,0,0,0

Since we cannot fit NAN's to our linear regression model, I will get rid of all the nan values in my data.

In [18]:
x.isna().sum()

Amount_Requested                  0
Amount_Funded_By_Investors        0
Monthly_Income                    1
Open_CREDIT_Lines                 2
Revolving_CREDIT_Balance          2
Inquiries_in_the_Last_6_Months    2
Loan_Length                       0
Debt_To_Income_Ratio              0
Employment_Length                 0
FICO_Range_Mean                   0
MORTGAGE                          0
NONE                              0
OTHER                             0
OWN                               0
RENT                              0
car                               0
credit_card                       0
debt_consolidation                0
educational                       0
home_improvement                  0
house                             0
major_purchase                    0
medical                           0
moving                            0
other                             0
renewable_energy                  0
small_business                    0
vacation                          0
wedding                           0
dtype: int64

In [19]:
x = x.fillna(0)

In [20]:
# Removed the NANs
x.isna().sum()

Amount_Requested                  0
Amount_Funded_By_Investors        0
Monthly_Income                    0
Open_CREDIT_Lines                 0
Revolving_CREDIT_Balance          0
Inquiries_in_the_Last_6_Months    0
Loan_Length                       0
Debt_To_Income_Ratio              0
Employment_Length                 0
FICO_Range_Mean                   0
MORTGAGE                          0
NONE                              0
OTHER                             0
OWN                               0
RENT                              0
car                               0
credit_card                       0
debt_consolidation                0
educational                       0
home_improvement                  0
house                             0
major_purchase                    0
medical                           0
moving                            0
other                             0
renewable_energy                  0
small_business                    0
vacation                          0
wedding                           0
dtype: int64

# Fitting the Model

In [21]:
y = y.iloc[:,].str.strip('%').astype(float)

In [22]:
y

81174      8.90
99592     12.12
80059     21.98
15825      9.99
33182     11.71
62403     15.31
48808      7.90
22090     17.14
76404     14.33
15867      6.91
94971     19.72
36911     14.27
41200     21.67
83869      8.90
53853      7.62
21399     15.65
62127     12.12
23446     10.37
44987      9.76
17977      9.99
86099     21.98
99483     19.05
28798     17.99
24168     11.99
10356     16.82
46027      7.90
2238      14.42
65278     15.31
4227       8.59
50182      7.90
          ...
84265     22.95
80231      7.90
49533     22.45
102514    15.13
78618     18.75
86953     14.09
80129     14.09
85216      8.90
38247     11.71
91245     15.80
53041      6.03
63051      6.62
14446      7.51
68628     14.33
98758     10.16
13070     10.75
45836     17.27
52330     19.99
48243     15.81
63256     18.75
42124     11.71
78043      7.62
925       10.08
74047     23.28
49957     14.65
23735     16.77
65882     14.09
55610     13.99
38576     12.42
3116      13.79
Name: Interest.Rate, Length: 2500, dtype: float64

In [23]:
y = y.rename(columns={'Interest.Rate':'Interest_Rate'}, inplace=True)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [25]:
predict_interest = LinearRegression().fit(X_train, y_train)

In [26]:
predict_interest.score(X_train, y_train)

0.7677736625899427

In [27]:
y_pred = predict_interest.predict(X_test)

In [28]:
r2_predict = r2_score(y_test, y_pred)
print('R2 Score:\t', r2_predict)

R2 Score:	 0.7584096395362063

In [29]:
mse_score = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:\t', mse_score)

Mean Squared Error:	 4.144100873270067

In [35]:
print('Coeffecients:\t', predict_interest.coef_[0:,])

Coeffecients:	 [ 3.99980273e-05  1.29929381e-04 -4.58673691e-05 -2.96203423e-02
 -5.72817259e-07  3.25369661e-01  1.30138622e-01 -9.27325522e-02
  4.91468489e-04 -8.80288594e-02 -9.01487367e-01  2.86179030e+00
 -5.63004304e-01 -6.22612593e-01 -7.74686034e-01 -1.79232014e-01
 -5.07051811e-01 -3.85366772e-01  4.33787358e-01 -4.10392096e-01
  1.01744450e+00  1.24599715e-01 -1.83636794e-01  4.02948858e-01
  3.60852953e-01  1.73694151e-02 -6.79584231e-03 -1.92497291e-01
 -4.92030178e-01]

In [46]:
print('There are 29 coefficients for our', x.shape[1], 'columns')

There are 29 coefficients for our 29 columns